### ISSUE TITLE
Failed to unpack addon

### ISSUE THREAD

**Issue by samueldcorbin** [ajour/ajour#631]
**Describe the bug**
Not sure if this is a problem on Ajour's or Townlong Yak's end, but the most recent version of Venture Plan fails to install. Downloading the addon from the website manually seems to work correctly.

**To Reproduce**
1. Attempt to update Townlong Yak's Venture Plan to 4.15a or install 4.15a from the catalogue

**Expected behavior**
Should unpack and install normally.

**Software involved**
Please complete the following information:
 - OS: Windows 10
 - Ajour version: 1.1.0

**Log Output**
23:26:30.456 [ajour::gui::update][DEBUG] Interaction::ModeSelected(Catalog)
23:26:33.733 [ajour::gui::update][DEBUG] Interaction::InstallAddon(Retail, Catalog { source: TownlongYak })
23:26:33.803 [ajour::gui::update][DEBUG] Message::CatalogInstallAddonFetched(Retail, "35")
23:26:33.803 [ajour_core::network][DEBUG] downloading remote version venture-plan-4.15a for 11779614220302842854
23:26:34.241 [ajour::gui::update][DEBUG] Message::DownloadedAddon((Retail, 11779614220302842854, error: false))
23:26:34.250 [ajour::gui::update][DEBUG] Message::UnpackedAddon((11779614220302842854, error: true))
23:26:34.250 [ajour][ERROR] Failed to unpack addon
23:26:34.250 [ajour][ERROR] caused by: invalid Zip archive

**Comment by tarkah** [comment]
@samueldcorbin We use the wowup.hub API which has addons / links for TownlongYak. We saw this same problem a few days back, were the wrong download links were in the API, which didn't resolve to the actual addon zip file.

So currently we are at the mercy of things getting fixed upstream with that API. Is this still a problem or does it work now?

**Comment by GurliGebis** [comment]
Still broken

**Comment by samueldcorbin** [comment]
Yes, still broken.

This is Townlong Yak's actual API: https://www.townlong-yak.com/addons/about/update-api

**Comment by tarkah** [comment]
@samueldcorbin We're aware of the official API. Unfortunately it's not really user friendly to work with from a client application. The creator of WowUp.Hub has integrated with the API already and is keeping his database in sync. So for now, we are just waiting for the download links to get fixed.

**Comment by samueldcorbin** [comment]
I am not really sure I understand what is user unfriendly - the API looks straightforward to me.

I was going to put in a ticket with WoWUp, but can't find anything involving Hub. Is the author aware of the problem?

**Comment by tarkah** [comment]
Yeah he should be aware of the problem. Thanks!

The problem with that API is that we can't directly query it for the latest release of a specific addon. For curse, tukui, wowi.. each addon has an ID associated to that source. You can query the source for that specific ID, and get the current latest version of the addon and download link to it. We can then compare that remote version to the local version to see if it's newer and should be updated.

With the TownlongYak API, there is an endpoint to get the "latest" release. For example with Venture Plan, this is the link:

https://www.townlong-yak.com/addons/api/install-bundle/venture-plan

The problem with that link is it doesn't contain any metadata about what version the addon is. So it's impossible for us to know if it's an update or not.

In order to do that, we have to use the `https://www.townlong-yak.com/addons/us/${bundle-token}` endpoint. The problem with this endpoint is it requires that we manage a bunch of state and continually poll it for updates within Ajour to figure out what the latest version actually is for the addon.

Since WowUp.Hub handles this already, and he's created endpoints where we can directly query the "latest file" for the addon w/ all the metadata we need, it was a MUCH easier implementation.

**Comment by samueldcorbin** [comment]
Looking at the API, the main problem I see is getting the initial list of addons - it doesn't look like there's any way to get an actual list of addons, and the documents even specify that the project identifiers (like "venture-plan") are not guaranteed to be stable.

But I'm not seeing what you mean about updating via the API. It looks a little bit obnoxious, but it doesn't look like you need to save a terribly large amount of state - just the persistent identifier for each addon (which you get during install) and a single "bundle token" for the entire repository.

When the user checks for updates, you extract the persistent identifiers from each installed TOC, get `/addons/us/${bundle-token}`, and just recursively process the resulting JSON, updating the data with the most recent update for each installed addon (including any revocations) and following the `next` key in the JSON until it's empty. Then whenever the user actually updates, just advance the saved value of that single bundle token to the most recent bundle token that includes all versions the user has currently installed.

**Comment by casperstorm** [comment]
I currently cant reproduce this. I just installed all of them, and the whole process went fine so I assume the dead URLs has been resolved.

**Comment by samueldcorbin** [comment]
I am still getting "Failed to unpack addon" when I try to install Venture Plan.

**Comment by casperstorm** [comment]
> Weird. I am still getting "Failed to unpack addon" when I try to install Venture Plan.

Hmm that's strange. I just installed it on my MacOS as well, does the other addons work from Yak?

**Comment by samueldcorbin** [comment]
No, every one gets stuck at Unpacking, with "Failed to unpack addon", and the log has an error for each attempted unpack too.

**Comment by layday** [comment]
> Then offer the user the most recent updates, and whenever the user actually installs an update, just advance the saved value of that single bundle token to the most recent bundle token that includes the current version of each townlong-yak addon the user currently has installed.

What happens when the user has installed a new add-on from TY while there were updates pending for installed add-ons?  If you replace the token you might skip over updates.  If you don't replace the token you might end up performing spurious updates.  If you store multiple tokens then you need to map them to add-ons.  If you update previously-installed add-ons when installing a new add-on you'd need to either do that for all add-ons or make an exception for TY, introducing complexity.

Then there's version numbers which feature left, right and centre in Ajour.  When you install an add-on from TY for the first time you get none, meaning you'll probably want to extract it from the TOC file if there's a `Version` entry in there or set it to a bogus value for display in the GUI and ignore it internally.

It's just a lot simpler to check if the installed version is equal to the remote version from metadata with a homogenous schema and add-on managers are architeched around this simpler workflow.

**Comment by samueldcorbin** [comment]
Ah, I checked and you're right, the "fv" value is not guaranteed to match the TOC Version value.

It looks like you do have to just associate a bundle token with each addon - so you have to save a whole two values for each addon: the persistent identifier and the bundle token its most recent update is associated with. But the logic is still straightforward: you just recurse through the bundle tokens, and memoize it since you don't know beforehand which addon's saved bundle token is the furthers back. No spurious updates, and you only traverse the JSON bundles once each time you check for updates.

In terms of version display, it seems like the best option would be to just use the TOC Version on install (substituting a dummy value if the TOC Version is empty). Then use the "fv" value for updating that field when you do updates. If you wanted to make it slightly more robust, run an update check for the previous addons at the same time as you install a new addon, and see if the persistent identifier for the new addon you're installing happens to be in your enumeration, which would give you an "fv" value, so you wouldn't need to use the TOC Version even on install.

Yes, it would be simpler if the API just returned current versions of every addon on offer, but it doesn't. The idea that depending on an intermediary service is simpler than just writing the slightly more complex API interaction seems pretty questionable to me, particularly when we're having this discussion because that intermediary broke. Sure, it makes the code _look_ simpler, but only because you added a dependency (one you don't control!).

**Comment by layday** [comment]
I'm not an Ajour dev, sorry if I've given off that impression - just the author of another add-on manager who was faced with the same dilemma and went with the WowUp Hub API.  So far we've found that to support the native TY API, one would have to:

* Hardcode the TY add-on IDs which are apparently not stable
* Forgo versions, publish dates and changelogs on first install and fudge the version number
* Divorce the install and update API calls
* Implement a drastically different workflow for updates which might mean having to rethink a lot of the manager abstractions
* Store one additional metadata entry per add-on
* Update metadata independently of add-on updates
* Potentially trace a trail of update tokens

For my add-on manager I'd also have to perform a database migration to add a token column or shoehorn the token in the version column.

----

Out of curiosity, are you able to download and extract the zip file from https://www.townlong-yak.com/addons/api/install-bundle/venture-plan?  The TY API is apparently returning a different URL to the WowUp Hub which is 404'ing for the WowUp author but not for me.

**Comment by samueldcorbin** [comment]
Sorry, I meant the generic "you" if that was unclear.

Yes, you would have to do those things. Ultimately _someone_ has to do those things either way - right now it's just being offloaded to a dependency (one that requires an external, active service to remain up and functional, and breaks if there's every a problem, like right now). And none of those things are that bad! Having to implement different logic for TY is annoying, but the logic is not terribly complicated or expensive.

The only one that really seems problematic is needing to track the addon IDs since there's no canonical list anywhere. I sent a message to the maintainer of townlong-yak about this to see if there's some way to get them because this seems pretty absurd.

Although ultimately, I guess I know I am shouting into the wind here.

Also yeah, I can retrieve the zip file successfully from there - just not via Ajour.

**Comment by layday** [comment]
The logic is not complicated _in isolation_.  When you have to do everything on that list to get one API with only a handful of add-ons sort of working, the wrapper API begins to sound very appealing.  I appreciate where you're coming from - I don't like layering abstraction upon abstraction -  but I am simply not motivated to do all of the work required and I don't think the Ajour folks are either.

**Comment by AcidWeb** [comment]
As maintainer of CurseBreaker I agree with the above statement. Work needed to fully and correctly implement his API is simply not worth the effort.

**Comment by samueldcorbin** [comment]
Would Ajour be open to a pull request? If I have some time in the next couple of weeks (which is decidedly 50/50), and I can find a way to get a list of addons, I can probably stomach enough Rust to write it.

It is an annoying API for sure, and it ought to be easier, but it isn't, and that looks unlikely to change. The author could publish to GitHub, but it doesn't seem that they will. We can is-ought all day, but that doesn't solve the problem. It's annoying to have to put in the effort, but these are pretty popular addons that ought to be supported, even if they're few in number (though that number is more than 2), and this is just not actually that massive an undertaking.

**Comment by casperstorm** [comment]
> Would Ajour be open to a pull request? If I have some time in the next couple of weeks (which is decidedly 50/50), and I can find a way to get a list of addons without hardcoding the paths, I can probably stomach enough Rust to write it.

You are welcome to take a stab and make a PR. That is one of the reasons we are open source.

**Comment by samueldcorbin** [comment]
Great! I asked only because I didn't want to spend the time on a PR for an approach you had already decided you'd definitely reject.

The next couple of days are going to determine how busy I am for the next few months, but I'll see if I can take a swing at it.

**Comment by tarkah** [comment]
I think as long as it's well thought out and conforms well with the flow of our program, I don't see any reason we would reject it. 

A few places to help point you in the right direction...

- All of our backends implement the `Backend` trait

https://github.com/ajour/ajour/blob/9093ddd0160a5dcc2493c413132cef0f338339f1/crates/core/src/repository/backend/mod.rs#L19-L28

- However, for efficiency and speed, we do "batch" queries of the APIs where possible and build the addon up from that. You can see the flow used here. Understanding this should touch on all the important pieces.

https://github.com/ajour/ajour/blob/9093ddd0160a5dcc2493c413132cef0f338339f1/crates/core/src/parse.rs#L39-L170

### Another consideration

Another thing that's important is how we populate the "catalog" with the TownlongYak addons, metadata and download links. This also comes from the Hub API. You can see how that's done here: https://github.com/ajour/ajour-catalog. We would need this to also conform to the native API.

In theory, if we ONLY updated this process to conform to the native API (managing state / update flow from here), we could just reference this catalog file from within Ajour to check for addon updates for TY. However, we may end up in the _exact_ situation the Hub API is in.

So maybe we can't have a centralized process for TY at all? Meaning we need to 100% manage the catalog & metadata for TY on the client side. This is my fear. It would add a lot of additional logic and requests at startup. We'd need to sync w/ that API on startup for EVERY client, to properly populate catalog and check updates against. Meaning this would need to run even when users don't have TY addons installed, to support the catalog. Unless we only trigger it once that catalog source is selected and the first TY addon is downloaded. As you can see, this gets complicated very fast.

Our goal for this program was always to be as simple and fast as possible. I won't lie that I'm not thrilled about the complexity and bloat adding this support would bring. And I'm not confident that API won't change in the future, or introduce breakages that will cause us to continually have to provide support. All for 2 addons.

So if you're still interested in proceeding, I'm more than happy to provide feedback and guidance on best way to integrate things w/ our program. But we will want to make sure it's minimal, doesn't disrupt the current flow of our program, and not something that results in unnecessary network requests, especially for those not using TY addons. We will also need to make sure the Catalog is taken care of as well.

**Comment by samueldcorbin** [comment]
That is very helpful, thanks.

Right now the catalog problem seems to be that you just can't query for a list of addons at all. And if there isn't some way to do that, or the author is unwilling to add one, then I'm not going to bother - I am not interested in maintaining a list of hardcoded paths because the author is _that_ stubborn. And if there is a way, then I don't see why it would be a problem to put it in the catalogue script.

I am unclear on something (without looking closer) - I see that the catalog updates at 00:00 UTC, but that's used for installation, not updates, right? If, for instance, a repository gets an update at 12:00 UTC, it doesn't take 12 hours for a user to be able to see it in Ajour, does it?

---
Also, again, it isn't 2 addons - Ajour already shows 8. Though the larger issue is probably that two are particularly popular, powerful addons that don't really have alternatives. Personally, I would not play WoW without OPie, and I would not use an addon manager that couldn't manage one of the most important popular addons I use, even if implementing that management is annoying. That's the whole point of an addon manage! It's annoying! I want a manager to do it for me!

**Comment by samueldcorbin** [comment]
Installation should be pretty trivial, as long as we can actually get a list of the paths - it doesn't require walking the bundle tokens (you don't have a bundle token _to_ walk from when you install the first addon!). And then we just store the bundle token as metadata for each addon install.

Then the repo should be simple. On the first update check, start from the associated bundle token, walk the chain to the present, find the most recent update (if any) in the chain, and save that bundle token. Next time, just check from _that_ bundle token. And memoize the walk up the chain so we're not walking the same nodes for multiple TY addons (which will share some amount of the end of the chain).
